// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1lFcMysQDm16ffSldlbYMIroq2ftGLLQ',
    appId: '1:969548958622:web:12ebf14d4451a86145a48f',
    messagingSenderId: '969548958622',
    projectId: 'instagramclone-41ac2',
    authDomain: 'instagramclone-41ac2.firebaseapp.com',
    storageBucket: 'instagramclone-41ac2.appspot.com',
    measurementId: 'G-BXV1E5YJXG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4q1LNQcIGI-oFL9vdKdOBqwYCx2xkm5Q',
    appId: '1:969548958622:android:b88d942ec636247145a48f',
    messagingSenderId: '969548958622',
    projectId: 'instagramclone-41ac2',
    storageBucket: 'instagramclone-41ac2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAP8Qakq0PbXBw9HGjIlYvwlTiI_NPltX8',
    appId: '1:969548958622:ios:4222904f9529db6f45a48f',
    messagingSenderId: '969548958622',
    projectId: 'instagramclone-41ac2',
    storageBucket: 'instagramclone-41ac2.appspot.com',
    androidClientId: '969548958622-91dr0ib4ice2adptrp0d92uj33bflun5.apps.googleusercontent.com',
    iosClientId: '969548958622-1dmaabhhsat55kl07ddbuqdvbv30a51n.apps.googleusercontent.com',
    iosBundleId: 'com.example.instagramClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAP8Qakq0PbXBw9HGjIlYvwlTiI_NPltX8',
    appId: '1:969548958622:ios:4222904f9529db6f45a48f',
    messagingSenderId: '969548958622',
    projectId: 'instagramclone-41ac2',
    storageBucket: 'instagramclone-41ac2.appspot.com',
    androidClientId: '969548958622-91dr0ib4ice2adptrp0d92uj33bflun5.apps.googleusercontent.com',
    iosClientId: '969548958622-1dmaabhhsat55kl07ddbuqdvbv30a51n.apps.googleusercontent.com',
    iosBundleId: 'com.example.instagramClone',
  );
}
